services:
  app-streamlit:
    build: .
    container_name: NC-Clivet_app
    restart: always
    volumes:
      - .:/app
      - ../.streamlit/secrets.toml:/app/.streamlit/secrets.toml:ro

  nginx:
    image: nginx:latest
    container_name: NC-Clivet_proxy
    restart: always
    ports:
      - "${PORTA_NGINX}:7443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../certs:/etc/nginx/certs:ro
    depends_on:
      - app-streamlit
