services:
  app-streamlit:
    build: .
    container_name: clivet_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      # Porto tutto fuori, non so se è meglio così ma al momento meno prono ad errori, poi valuterò
      - ../.streamlit/secrets.toml:/app/.streamlit/secrets.toml:ro
    restart: always
